services:
  redis:
    image: redis:7
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: redis-cli ping
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes: 
      - redis:/data
volumes:
  redis: {}